In [1]:
import gym
env = gym.make('CartPole-v0')
for i_episode in range(20):
    observation = env.reset()
    for t in range(100):
        env.render()
#         print(observation)
        action = env.action_space.sample()
        print env.action_space
        observation, reward, done, info = env.step(action)
        
        if done:
            print("Episode finished after {} timesteps".format(t+1))
            break

INFO:gym.envs.registration:Making new env: CartPole-v0
[2016-06-29 15:53:48,270] Making new env: CartPole-v0


Discrete(2)
Discrete(2)
Discrete(2)
Discrete(2)
Discrete(2)
Discrete(2)
Discrete(2)
Discrete(2)
Discrete(2)
Discrete(2)
Discrete(2)
Discrete(2)
Discrete(2)
Episode finished after 13 timesteps
Discrete(2)
Discrete(2)
Discrete(2)
Discrete(2)
Discrete(2)
Discrete(2)
Discrete(2)
Discrete(2)
Discrete(2)
Discrete(2)
Discrete(2)
Discrete(2)
Discrete(2)
Discrete(2)
Discrete(2)
Discrete(2)
Discrete(2)
Discrete(2)
Episode finished after 18 timesteps
Discrete(2)
Discrete(2)
Discrete(2)
Discrete(2)
Discrete(2)
Discrete(2)
Discrete(2)
Discrete(2)
Discrete(2)
Discrete(2)
Discrete(2)
Discrete(2)
Discrete(2)
Discrete(2)
Discrete(2)
Discrete(2)
Discrete(2)
Discrete(2)
Discrete(2)
Discrete(2)
Discrete(2)
Discrete(2)
Discrete(2)
Discrete(2)
Discrete(2)
Episode finished after 25 timesteps
Discrete(2)
Discrete(2)
Discrete(2)
Discrete(2)
Discrete(2)
Discrete(2)
Discrete(2)
Discrete(2)
Discrete(2)
Discrete(2)
Discrete(2)
Discrete(2)
Discrete(2)
Discrete(2)
Discrete(2)
Discrete(2)
Discrete(2)
Discrete(2)
Disc

In [3]:
import gym
env = gym.make('CartPole-v0')
print(env.action_space)
#> Discrete(2)
print(env.observation_space)
#> Box(4,)

INFO:gym.envs.registration:Making new env: CartPole-v0
[2016-06-22 17:31:12,412] Making new env: CartPole-v0


Discrete(2)
Box(4,)


In [1]:
import gym
env = gym.make('Pong-v0')
# env.monitor.start('/tmp/cartpole-experiment-1')
for i_episode in range(2000):
    observation = env.reset()
    print observation
    while True:
        env.render()
        action = env.action_space.sample()
        observation, reward, done, info = env.step(action)
        if done:
#             print("Game finished")
            break

# env.monitor.close()

INFO:gym.envs.registration:Making new env: Pong-v0
[2016-06-29 17:34:32,354] Making new env: Pong-v0


[[[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ..., 
  [109 118  43]
  [109 118  43]
  [109 118  43]]

 [[109 118  43]
  [109 118  43]
  [109 118  43]
  ..., 
  [109 118  43]
  [109 118  43]
  [109 118  43]]

 [[109 118  43]
  [109 118  43]
  [109 118  43]
  ..., 
  [109 118  43]
  [109 118  43]
  [109 118  43]]

 ..., 
 [[ 53  95  24]
  [ 53  95  24]
  [ 53  95  24]
  ..., 
  [ 53  95  24]
  [ 53  95  24]
  [ 53  95  24]]

 [[ 53  95  24]
  [ 53  95  24]
  [ 53  95  24]
  ..., 
  [ 53  95  24]
  [ 53  95  24]
  [ 53  95  24]]

 [[ 53  95  24]
  [ 53  95  24]
  [ 53  95  24]
  ..., 
  [ 53  95  24]
  [ 53  95  24]
  [ 53  95  24]]]
[[[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ..., 
  [109 118  43]
  [109 118  43]
  [109 118  43]]

 [[109 118  43]
  [109 118  43]
  [109 118  43]
  ..., 
  [109 118  43]
  [109 118  43]
  [109 118  43]]

 [[109 118  43]
  [109 118  43]
  [109 118  43]
  ..., 
  [109 118  43]
  [109 118  43]
  [109 118  43]]

 ..., 
 [[ 53  95  24]
  [ 53  95  24]


KeyboardInterrupt: 

In [37]:
print(env.observation_space)


Box(4,)


In [22]:
print(env.observation_space.low)

[-4.8               -inf -0.41887902        -inf]


In [1]:
import gym
import numpy as np
env = gym.make('CartPole-v0')
def eval(env,w,render=False,steps = 200):
    observation = env.reset()
    cum_reward = 0.0
    for i in range(steps):
        if render:
            env.render()
        w_sum = np.sum(w*observation)
        action = 1 if w_sum > 0 else 0
        observation, reward, done, info = env.step(action)
        cum_reward += reward
        if done:
            break
    return cum_reward
#searching for the best cumulative reward across random configurations
w_hat = None # best model
best_reward = 0.0
for i_episode in range(10000):
    w = np.random.rand(1,4)
    cum_reward = eval(env,w)
    if cum_reward > best_reward:
            best_reward = cum_reward
            w_hat = w

print("The best reward is {}".format(best_reward))
print(w_hat)
#env.monitor.start('/tmp/cartpole-experiment-1')
eval(env,w_hat,render=True,steps = 10000)
#env.monitor.close()

INFO:gym.envs.registration:Making new env: CartPole-v0
[2016-06-22 18:11:34,406] Making new env: CartPole-v0
[2016-06-22 18:12:13,966] You are calling 'step()' even though this environment has already returned done = True. You should always call 'reset()' once you receive 'done = True' -- any further steps are undefined behavior.


The best reward is 200.0
[[ 0.71432833  0.20705438  0.87006381  0.73839744]]


0.0

In [8]:
import numpy as np
import gym

env = gym.make("Pong-v0")
observation = env.reset()
print observation



INFO:gym.envs.registration:Making new env: Pong-v0
[2016-06-29 18:28:08,535] Making new env: Pong-v0


[[[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ..., 
  [109 118  43]
  [109 118  43]
  [109 118  43]]

 [[109 118  43]
  [109 118  43]
  [109 118  43]
  ..., 
  [109 118  43]
  [109 118  43]
  [109 118  43]]

 [[109 118  43]
  [109 118  43]
  [109 118  43]
  ..., 
  [109 118  43]
  [109 118  43]
  [109 118  43]]

 ..., 
 [[ 53  95  24]
  [ 53  95  24]
  [ 53  95  24]
  ..., 
  [ 53  95  24]
  [ 53  95  24]
  [ 53  95  24]]

 [[ 53  95  24]
  [ 53  95  24]
  [ 53  95  24]
  ..., 
  [ 53  95  24]
  [ 53  95  24]
  [ 53  95  24]]

 [[ 53  95  24]
  [ 53  95  24]
  [ 53  95  24]
  ..., 
  [ 53  95  24]
  [ 53  95  24]
  [ 53  95  24]]]
