In [2]:
import gym
env = gym.make('MountainCar-v0')
env.reset()
for _ in range(1000):
    env.render()
    env.step(env.action_space.sample()) # take a random action

INFO:gym.envs.registration:Making new env: MountainCar-v0
[2016-06-20 19:35:10,537] Making new env: MountainCar-v0


In [3]:
import gym
env = gym.make('CartPole-v0')
for i_episode in range(20):
    observation = env.reset()
    for t in range(100):
        env.render()
        print(observation)
        action = env.action_space.sample()
        observation, reward, done, info = env.step(action)
        
        if done:
            print("Episode finished after {} timesteps".format(t+1))
            break

INFO:gym.envs.registration:Making new env: CartPole-v0
[2016-06-22 17:35:28,852] Making new env: CartPole-v0


1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
Episode finished after 18 timesteps
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
Episode finished after 17 timesteps
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
Episode finished after 25 timesteps
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
Episode finished after 12 timesteps
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
Episode finished after 33 timesteps
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
Episode finished after 28 timesteps
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
Episode finished after 38 timesteps
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0


In [3]:
import gym
env = gym.make('CartPole-v0')
print(env.action_space)
#> Discrete(2)
print(env.observation_space)
#> Box(4,)

INFO:gym.envs.registration:Making new env: CartPole-v0
[2016-06-22 17:31:12,412] Making new env: CartPole-v0


Discrete(2)
Box(4,)


In [4]:
import gym
env = gym.make('CartPole-v0')
env.monitor.start('/tmp/cartpole-experiment-1')
for i_episode in range(20):
    observation = env.reset()
    for t in range(100):
        env.render()
        print(observation)
        action = env.action_space.sample()
        observation, reward, done, info = env.step(action)
        if done:
            print("Episode finished after {} timesteps".format(t+1))
            break

env.monitor.close()

INFO:gym.envs.registration:Making new env: CartPole-v0
[2016-06-22 17:42:16,669] Making new env: CartPole-v0
INFO:gym.monitoring.monitor:Creating monitor directory /tmp/cartpole-experiment-1
[2016-06-22 17:42:16,676] Creating monitor directory /tmp/cartpole-experiment-1
INFO:gym.monitoring.video_recorder:Starting new video recorder writing to /tmp/cartpole-experiment-1/openaigym.video.0.8507.video000000.mp4
[2016-06-22 17:42:16,684] Starting new video recorder writing to /tmp/cartpole-experiment-1/openaigym.video.0.8507.video000000.mp4


[ 0.02733092 -0.0151045   0.0443131  -0.0144665 ]
[ 0.02702883  0.17935485  0.04402377 -0.2928454 ]
[ 0.03061592  0.37382237  0.03816686 -0.57132525]
[ 0.03809237  0.17818658  0.02674036 -0.26686694]
[ 0.0416561  -0.0173066   0.02140302  0.03412873]
[ 0.04130997 -0.21272884  0.02208559  0.33348695]
[ 0.0370554  -0.40815805  0.02875533  0.63305192]
[ 0.02889223 -0.6036691   0.04141637  0.93465016]
[ 0.01681885 -0.79932452  0.06010937  1.24005454]
[  8.32361686e-04  -6.05023730e-01   8.49104626e-02   9.66791241e-01]
[-0.01126811 -0.41113838  0.10424629  0.70194467]
[-0.01949088 -0.60753894  0.11828518  1.02553913]
[-0.03164166 -0.80402019  0.13879596  1.35289644]
[-0.04772206 -1.00058486  0.16585389  1.68558312]

INFO:gym.monitoring.video_recorder:Starting new video recorder writing to /tmp/cartpole-experiment-1/openaigym.video.0.8507.video000001.mp4
[2016-06-22 17:42:17,411] Starting new video recorder writing to /tmp/cartpole-experiment-1/openaigym.video.0.8507.video000001.mp4



[-0.06773376 -1.19719229  0.19956555  2.02498521]
Episode finished after 15 timesteps
[ 0.01879188 -0.04613235 -0.01442707 -0.02236011]
[ 0.01786924  0.14919349 -0.01487427 -0.3195598 ]
[ 0.02085311 -0.0457135  -0.02126546 -0.03160452]
[ 0.01993884 -0.24052414 -0.02189755  0.25429379]
[ 0.01512835 -0.04509648 -0.01681168 -0.04521478]
[ 0.01422642 -0.23997338 -0.01771597  0.24211685]
[ 0.00942696 -0.04460291 -0.01287364 -0.05610109]
[ 0.0085349   0.15070124 -0.01399566 -0.35281778]
[ 0.01154892 -0.04421892 -0.02105201 -0.06458076]
[ 0.01066455 -0.23903282 -0.02234363  0.22138649]
[ 0.00588389 -0.04359874 -0.0179159  -0.07825993]
[ 0.00501191  0.1517754  -0.0194811  -0.37654111]
[ 0.00804742 -0.04306451 -0.02701192 -0.09006376]
[ 0.00718613  0.15243399 -0.0288132  -0.39114508]
[ 0.01023481 -0.04226744 -0.0366361  -0.10768406]
[ 0.00938946 -0.23684576 -0.03878978  0.17321896]
[ 0.00465255 -0.04119073 -0.0353254  -0.13144415]
[ 0.00382873  0.15441897 -0.03795428 -0.43505916]
[ 0.00691711 

INFO:gym.monitoring.video_recorder:Starting new video recorder writing to /tmp/cartpole-experiment-1/openaigym.video.0.8507.video000008.mp4
[2016-06-22 17:42:18,837] Starting new video recorder writing to /tmp/cartpole-experiment-1/openaigym.video.0.8507.video000008.mp4



[ 0.06716607  0.38569878 -0.16377191 -1.0166237 ]
[ 0.07488005  0.58258035 -0.18410438 -1.35592843]
Episode finished after 24 timesteps
[ 0.04399786 -0.00156186 -0.04783765  0.01048413]
[ 0.04396662  0.19421235 -0.04762797 -0.29690013]
[ 0.04785087  0.38997976 -0.05356597 -0.60421557]
[ 0.05565046  0.19564624 -0.06565028 -0.32887427]
[ 0.05956339  0.00151732 -0.07222777 -0.0575955 ]
[ 0.05959373  0.19759657 -0.07337967 -0.37216403]
[ 0.06354567  0.00358962 -0.08082296 -0.10349099]
[ 0.06361746  0.19977123 -0.08289278 -0.42053888]
[ 0.06761288  0.00591561 -0.09130355 -0.15509646]
[ 0.06773119  0.20221817 -0.09440548 -0.47512979]
[ 0.07177556  0.00854726 -0.10390808 -0.21363103]
[ 0.0719465   0.20498945 -0.1081807  -0.53719905]
[ 0.07604629  0.01154151 -0.11892468 -0.28046655]
[ 0.07627712  0.20814137 -0.12453401 -0.60816491]
[ 0.08043995  0.40476412 -0.13669731 -0.9373334 ]
[ 0.08853523  0.60143814 -0.15544398 -1.26965636]
[ 0.100564    0.79816514 -0.1808371  -1.60670563]
Episode finis

INFO:gym.monitoring.monitor:Finished writing results. You can upload them to the scoreboard via gym.upload('/tmp/cartpole-experiment-1')
[2016-06-22 17:42:19,871] Finished writing results. You can upload them to the scoreboard via gym.upload('/tmp/cartpole-experiment-1')



[-0.10717002  0.22681585  0.12845369  0.01412292]
[-0.1026337   0.41988399  0.12873615 -0.23543169]
[-0.09423602  0.22318027  0.12402751  0.09492626]
[-0.08977241  0.41632647  0.12592604 -0.15619687]
[-0.08144589  0.21964757  0.1228021   0.17340993]
[-0.07705293  0.02300161  0.1262703   0.50217071]
[-0.0765929   0.2161387   0.13631371  0.25179646]
[-0.07227013  0.01936023  0.14134964  0.58417832]
[-0.07188292  0.21224871  0.15303321  0.33914974]
[-0.06763795  0.01531808  0.15981621  0.67590982]
[-0.06733159 -0.18162118  0.1733344   1.01434039]
[-0.07096401  0.01081867  0.19362121  0.78071164]
[-0.07074764 -0.18636262  0.20923544  1.12752639]
Episode finished after 28 timesteps
[-0.04475252 -0.02880996  0.01593662  0.00864413]
[-0.04532872 -0.2241568   0.01610951  0.30631235]
[-0.04981185 -0.02926806  0.02223575  0.01875317]
[-0.05039721 -0.22470173  0.02261082  0.31836797]
[-0.05489125 -0.42013829  0.02897818  0.6180949 ]
[-0.06329401 -0.22543286  0.04134007  0.33467776]
[-0.06780267 

In [37]:
print(env.observation_space)


Box(4,)


In [22]:
print(env.observation_space.low)

[-4.8               -inf -0.41887902        -inf]


In [1]:
import gym
import numpy as np
env = gym.make('CartPole-v0')
def eval(env,w,render=False,steps = 200):
    observation = env.reset()
    cum_reward = 0.0
    for i in range(steps):
        if render:
            env.render()
        w_sum = np.sum(w*observation)
        action = 1 if w_sum > 0 else 0
        observation, reward, done, info = env.step(action)
        cum_reward += reward
        if done:
            break
    return cum_reward
#searching for the best cumulative reward across random configurations
w_hat = None # best model
best_reward = 0.0
for i_episode in range(10000):
    w = np.random.rand(1,4)
    cum_reward = eval(env,w)
    if cum_reward > best_reward:
            best_reward = cum_reward
            w_hat = w

print("The best reward is {}".format(best_reward))
print(w_hat)
#env.monitor.start('/tmp/cartpole-experiment-1')
eval(env,w_hat,render=True,steps = 10000)
#env.monitor.close()

INFO:gym.envs.registration:Making new env: CartPole-v0
[2016-06-22 18:11:34,406] Making new env: CartPole-v0
[2016-06-22 18:12:13,966] You are calling 'step()' even though this environment has already returned done = True. You should always call 'reset()' once you receive 'done = True' -- any further steps are undefined behavior.


The best reward is 200.0
[[ 0.71432833  0.20705438  0.87006381  0.73839744]]


0.0

In [1]:
import numpy as np
import gym

env = gym.make("Pong-v0")
observation = env.reset()
for i in range(2000):
    print len(observation)
    env.render()


INFO:gym.envs.registration:Making new env: Pong-v0
[2016-06-27 23:26:35,928] Making new env: Pong-v0


210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210
210


KeyboardInterrupt: 